restoran/members/urls.py
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from django.conf import settings


app_name = 'members'

urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('register_user', views.register_user, name='register_user')

]

restoran/posts/urls.py
from django.urls import path
from . import views


from django.conf.urls.static import static
from django.conf import settings

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_restoran', views.add_restoran, name='add_restoran'),
    path('add_score', views.add_score, name='add_score'),
    path('help', views.help, name='help'),
    path('id/<int:id>/', views.id_restoran, name='id_restoran'),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restoran/restoran/urls.py
from django.urls import path, include

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    

    
]

restoran/templates/includes/footer.html
<footer style="background-color: #f5f5f5; border-top: 1px solid #dddddd; padding: 20px 0; text-align: center;">
    <p>© 2024 НТЦ-1</p>    
</footer>

restoran/templates/includes/header.html
{% load static %}
<header>  
      <nav class="navbar navbar-expand-lg bg-body-tertiary" >
        <div class="container-fluid" >
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="60" height="60" >Рестораны </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'posts:add_restoran' %}">Добавление ресторана</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:add_score' %}" >Добавить оценку</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:help' %}" >Забыл оценку</a>
              </li>
          
            </ul>
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'members:logout' %}">
              <span > {{ request.user.username }} | Выйти</span>
            </a>
            {% else  %}
            <a class="navbar-brand" href="{% url 'members:register_user' %} ">
              <span>Зарегистрироваться</span>
              <a class="navbar-brand" href="{% url 'members:login' %} ">
              <span>Войти</span>
            </a>
            {% endif %} 
          </div>
        </div>
      </nav>

      <br>
      <div class="container">
        {% if messages  %}
          {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
          {% endfor %}
        {% endif %}
      </div>

      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      
</header>