restoran/posts/urls.py
from django.urls import path
from . import views


from django.conf.urls.static import static
from django.conf import settings

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_restoran', views.add_restoran, name='add_restoran'),
    path('add_score', views.add_score, name='add_score'),
    path('help', views.help, name='help'),
    path('id/<int:id>/', views.id_restoran, name='id_restoran'),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restoran/restoran/urls.py
from django.urls import path, include

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    

    
]

restoran/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

User = get_user_model()  

class restorans(models.Model):
    name =  models.CharField(max_length=40)
    image = models.ImageField(upload_to='pictures/', blank=True, null=True)
 
    def __str__(self):
        return self.name
    

class person(models.Model):
    name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    patronymic = models.CharField(max_length=10)
    tabel = models.IntegerField(
        default=9999,
        validators=[MaxValueValidator(9999)]
    )
    
    def __str__(self):
        return self.name
    
class Score(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, default='Гость')
    name_restoran = models.ForeignKey(restorans, on_delete=models.CASCADE)
    dish_name = models.CharField(max_length=100, blank=True, null=True, default='Всё подряд.')
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 11)])
    data = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        formatted_date = self.data.strftime("%d.%m.%Y")
        return f"{self.name} - {self.name_restoran} - {self.dish_name} - {self.rating} - {formatted_date} "

restoran/posts/forms.py
from django import forms 
from .models import *

class AddRestoranForm(forms.ModelForm):
    class Meta:
        model = restorans
        fields = ['name', 'image']
        widgets = {
            'image': forms.FileInput(attrs={'accept': 'image/*'})
        }
        widgets = {
            'name': forms.TextInput(attrs={ 'style': 'width: 300px;'})
        }
        labels = {
            'name': 'Имя',
            'image': 'Картинка',
        }


class AddScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['name', 'name_restoran', 'dish_name', 'rating']
        labels = {
            'name': 'Имя',
            'name_restoran': 'Название ресторана',
            'dish_name': 'Название блюда',
            'rating': 'Рейтинг',
        }
    
    def __init__(self, *args, **rwargs):
        super(AddScoreForm, self).__init__(*args, **rwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name_restoran'].widget.attrs['class'] = 'form-control'
        self.fields['dish_name'].widget.attrs['class'] = 'form-control'
        self.fields['rating'].widget.attrs['class'] = 'form-control'

        

restoran/posts/views.py
from django.shortcuts import redirect, render
from django.db.models import Avg, Count, Max, Min
from .forms import *
from .models import restorans
from django.contrib.auth.decorators import login_required
import random

from django.db import IntegrityError

def index(request):
    # restaurants_with_ratings = restorans.objects.annotate(avg_rating=Avg('score__rating'))
    # top_three = Score.objects.values('name_restoran__name').annotate(avg_rating=Avg('rating'), total_ratings=Count('rating')).order_by('-avg_rating', '-total_ratings')[:3]
    # random_restaurants = random.sample(restaurants_with_ratings, min(len(restaurants_with_ratings), 3))

    restaurants_with_ratings = list(restorans.objects.annotate(avg_rating=Avg('score__rating')))
    top_three = Score.objects.values('name_restoran__name').annotate(avg_rating=Avg('rating'), total_ratings=Count('rating')).order_by('-avg_rating', '-total_ratings')[:3]
    # random_restaurants = random.sample(restaurants_with_ratings, min(len(restaurants_with_ratings), 3))
    random.shuffle(restaurants_with_ratings)
    
    context = {
        'restaurants_with_ratings':restaurants_with_ratings,
        'top_three':top_three,

    }

    return render(request, 'posts/index.html', context)

def add_restoran(request):
    if request.method == "POST":
        form = AddRestoranForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('posts:index')
            except IntegrityError as e:
                form.add_error(None, f'Ошибка добавления: {e}')
    else:
        form = AddRestoranForm()
    return render(request, 'posts/add_restoran.html', {'form': form})

def add_score(request):
    if request.method == "POST":
        form = AddScoreForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                score = form.save(commit=False)
                if request.user.is_authenticated:
                    score.name = request.user.username
                score.save()
                return redirect('posts:index')
            except IntegrityError as e:
                form.add_error(None, f'Ошибка добавления: {e}')
    else:
        if request.user.is_authenticated:
            initial_data = {'name': request.user.username}
            form = AddScoreForm(initial=initial_data)
        else:
            form = AddScoreForm()
    return render(request, 'posts/add_score.html', {'form': form})


# def add_score(request):
#     if request.method == "POST":
#         form = AddScoreForm(request.POST, request.FILES)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect('posts:index')
#             except IntegrityError as e:
#                 form.add_error(None, f'Ошибка добавления: {e}')
#     else:
#         form = AddScoreForm()
#     return render(request, 'posts/add_score.html', {'form': form})


def help(request):
    return render(request, 'posts/help.html')

def id_restoran(request, id):
    
    zakazi = Score.objects.filter(name_restoran_id=id)
    all_score = zakazi.count()

    get_restoran = restorans.objects.get(id=id)
    restoran_name = get_restoran.name
    latest_score = Score.objects.latest('data')
    last_date = latest_score.data
    formatted_last_date = last_date.strftime("%d.%m.%Y")
    all_table = Score.objects.all()
    all_table = Score.objects.filter(name_restoran=id).order_by('-data')
    max_rating = Score.objects.filter(name_restoran_id=id).aggregate(max_rating=Max('rating'))['max_rating']
    min_rating = Score.objects.filter(name_restoran_id=id).aggregate(min_rating=Min('rating'))['min_rating']
    avg_rating = Score.objects.filter(name_restoran_id=id).aggregate(avg_rating=Avg('rating'))['avg_rating']



    context={
        'zakazi': zakazi,
        'all_score': all_score,
        'restoran_name': restoran_name,
        'formatted_last_date': formatted_last_date,
        'get_restoran': get_restoran,
        'all_table': all_table,
        'max_rating': max_rating,
        'min_rating': min_rating,
        'avg_rating': avg_rating,
    }
    return render(request, 'posts/id_restoran.html', context )

restoran/templates/posts/add_restoran.html
{% extends 'base.html' %}
{% block content %}
{{ context }}
<br>
<div style="text-align: center;">
     <h1>Добавьте название ресторана</h1>
<form action="{% url 'posts:add_restoran' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <div style="display: flex; justify-content: center;">
        <button type="submit" class="btn btn-primary">Добавить</button>
    </div>
    
    
</form>
<br>
</div>
{% endblock %}

restoran/templates/posts/add_score.html
{% extends 'base.html' %}
{% block content %}
{{ context }}
<br>
<div style="text-align: center;">
     <h1>Добавьте оценку</h1>
</div>


<div style="max-width: 800px; margin: 0 auto;">     
    <form action="{% url 'posts:add_score' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <div style="display: flex; justify-content: center;">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
        
        
    </form>
<br>
</div>
{% endblock %}

restoran/templates/posts/help.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
<br>
    <style>
        h1 {
         text-align: center;
        }
        </style>
<h1 >Оценка еды</h1>
<ol>
    <li>Отвратительно: блюдо несъедобное, вызывает неприятные ощущения и отвращение.</li>
    <li>Скверно: блюдо имеет заметные недостатки во вкусе, текстуре или подаче, что делает его неприятным для употребления.</li>
    <li>Не очень хорошо: блюдо имеет некоторые недостатки, но в целом приемлемо на вкус и может быть оценено как «удовлетворительно».</li>
    <li>Средне: блюдо имеет нейтральный вкус и текстуру, не вызывает сильных эмоций, но и не запоминается.</li>
    <li>Хорошо: блюдо обладает приятным вкусом и консистенцией, достаточно сбалансировано, чтобы удовлетворить основные вкусовые рецепторы. Внешний вид привлекательный, но не вызывает особого восхищения.</li>
    <li>Очень хорошо: блюдо имеет отличный вкус и консистенцию, хорошо сбалансировано и вызывает положительные эмоции. Внешний вид привлекательный и вызывает интерес.</li>
    <li>Отлично: блюдо обладает превосходным вкусом и консистенцией, идеально сбалансировано и вызывает восхищение. Внешний вид привлекательный и вызывает желание попробовать.</li>
    <li>Великолепно: блюдо имеет исключительный вкус и консистенцию, является шедевром кулинарного искусства и вызывает восторг. Внешний вид потрясающий и незабываемый.</li>
    <li>Изумительно: блюдо настолько великолепно, что становится незабываемым и вызывает желание поделиться им с другими. Внешний вид блюда. Настолько потрясающий, что его хочется запечатлеть на фото или описать друзьям.</li>
    <li>Гастрономический оргазм: блюдо настолько превосходно, что вызывает исколоколо желание попробовать ещё раз. Внешний вид блюда настолько великолепно, что кажется, будто оно сошло со страниц кулинарной книги.</li>
</ol>
</div>
{% endblock %}

restoran/templates/posts/id_restoran.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div style="text-align: center;">
        <h1>{{ get_restoran.name }}</h1>
    </div>

    
    <div style="overflow: auto;">
        <div style="float: left; margin-right: 20px;"> <!-- Контейнер для изображения -->
            {% if get_restoran.image %}
                <img src="{{ get_restoran.image.url }}" width="500" height="500" alt="Изображение ресторана"> <!-- Изображение -->
            {% else %}
                <img src="{% static 'img/no_jmg.png' %}"  width="500" height="500" alt="Изображение отсутствует">
            {% endif %}
        </div>






        
        <div style="float: center;"> 
            Всего оценок: {{ all_score }} <br>
            Последний заказ: {{ formatted_last_date }} <br>
            Средний рейтинг рейтинг: {{ avg_rating|floatformat:"1" }} <br>
            Максимальный рейтинг: {{ max_rating }} <br>
            Минимальный рейтинг: {{ min_rating }} <br>
            
        </div>
    </div>
    <div style="text-align: center;">
        <br><br>
        <h1>Все оценки </h1>
    </div>
    <style>
        table {
            margin: 0 auto; /* Центрируем таблицу по горизонтали */
        }
    </style>
    
    <table  class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Кто поставил</th>
          <th scope="col">Название блюда</th>
          <th scope="col">Рейтинг</th>
          <th scope="col">Дата</th>
        </tr>
      </thead>
      <tbody>
        {% for item in all_table %}
            <th scope="row">{{ forloop.counter }}</th>
            <td  scope="row">{{ item.name }}</td>
            <td  scope="row">{{ item.dish_name }}</td>
            <td  scope="row">{{ item.rating }}</td>
            <td scope="row">{{ item.data|date:"d.m.Y" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>



{% endblock %}

restoran/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
{{ context }}

<div class="row">
<div style="display: flex; flex-wrap: wrap;" class="main-block col-10">
  {% for restoran in restaurants_with_ratings %}
    <div style="flex: 0 0 33.33%; text-align: center; padding: 10px;">
      <div style="display: inline-block;">
        
        {% if restoran.image %}
          <img src="{{ restoran.image.url }}" alt="{{ restoran.name }}" width="300" height="300" style="border-radius: 50%;">
        {% endif %}
        <h3>{{ restoran.name }}</h3>
        <p><h5>Средняя оценка: {{ restoran.avg_rating|floatformat:"1" }} </h5></p>
        <p><a href="{% url 'posts:id_restoran' restoran.id %}">Все оценки ресторана</a></p>
      </div>
    </div>
  {% endfor %}
  </div>


  <div class="block col-2" > 
    <span class="text-color" style="display: block; text-align: center;">TOP заведений:</span>
    <ul style="list-style: none;">
        {% for i in top_three %}
            {% if forloop.counter == 1 %}
                <li> <img src="/static/img/gold.png" width="20" height="20"> {{  i.name_restoran__name }} - {{ i.avg_rating|floatformat:"1" }} </li>
            {% elif forloop.counter == 2 %}
                <li> <img src="/static/img/silver.png" width="20" height="20"> {{ i.name_restoran__name }} - {{ i.avg_rating|floatformat:"1" }}</li>
            {% elif forloop.counter == 3 %}
                <li> <img src="/static/img/bronze.png" width="20" height="20"> {{ i.name_restoran__name }} - {{ i.avg_rating|floatformat:"1"}}</li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

</div>

{% endblock %}